# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Translations for DCS at Bates
baseurl: "/translations/" # the subpath of your site, e.g. /blog/
url: "http://shrouta.github.io" # the base hostname & protocol for your site
twitter_username: anelisehshrout
github_username:  shrouta

# Build settings
markdown: kramdown
permalink: /translations/:year/:month/:day/:title
